### ISSUE TITLE
Ultrawide Broken after SF6 Update

### ISSUE THREAD

**Issue by ssspncr** [praydog/REFramework#1350]
SF6's latest update breaks this mod's ultrawide support.

**Comment by mbushnaq00** [comment]
yes same here, hopefully a new nightly build gets released soon with a fix

**Comment by firstnamesonly** [comment]
was looking around to see if others were having the same issue, glad to know its not just me

**Comment by Jval85** [comment]
good to know, having the same issue.

**Comment by AT-4** [comment]
Confirming issue here too

**Comment by praydog** [comment]
Does the nightly build here work with it? I'm not noticing issues with it: https://github.com/praydog/REFramework-nightly/releases/

What issue is occurring?

**Comment by firstnamesonly** [comment]
ill try the build real quick and let you know, im not sure actually how old the one i had was

**Comment by firstnamesonly** [comment]
![Image](https://github.com/user-attachments/assets/d9948bf2-b47e-4624-bd8a-60052a88c4e3)
downloaded the latest build and i cant seem to get ultrawide to display properly seems constrained to 16:9 no matter what i do

**Comment by praydog** [comment]
Upload your `re2_framework_log.txt` please. It's in your game folder.

**Comment by firstnamesonly** [comment]
keeps failing to upload :(

**Comment by lwrand** [comment]
Same issue, here is my log:

[re2_framework_log.txt](https://github.com/user-attachments/files/20618871/re2_framework_log.txt)

**Comment by raziezel** [comment]
[re2_framework_log.txt](https://github.com/user-attachments/files/20618962/re2_framework_log.txt)

Same for me if a comparison helps. Thanks for this 
Did also uninstall SF6, delete the game folder and started from scratch and didn't make a difference

**Comment by praydog** [comment]
Fixed in e4d00a5a774e1a1b64cce53023256129dbf18177

Download from https://github.com/praydog/REFramework-nightly/releases/

**Comment by AT-4** [comment]
Thank you for your hard work as always!

**Comment by firstnamesonly** [comment]
thanks dog appreciate ya

**Comment by raziezel** [comment]
thank you!

**Comment by GusBZ** [comment]
Hi . Was  This  fixed for good ? Because I am having the same issue in my steam deck oled . The grey line top and down still present in the game.
