### ISSUE TITLE
Black Screen on MHWilds when entering the game

### ISSUE THREAD

**Issue by davisantos2000-ops** [praydog/REFramework#1468]
**Describe the bug**
When I boot the game it loads but doesn't reach the menu screen. Works without loose file loader, but the files I have downloaded require it.

**Upload logs and any crash dumps**
Locate the `re2_framework_log.txt` in your game directory and upload it along with the issue.
If you crashed, upload the `reframework_crash.dmp` file as

[re2_framework_log.txt](https://github.com/user-attachments/files/24200727/re2_framework_log.txt)

**Identify the REFramework version**
REFramework sha256:fc4463fe5ef39698465587e0f62137cff8a3019d1dddc549496c1c1a088bc7e3

**To Reproduce**
1. Fluffy Mod Manager
2. Launch Game
3. See error

**Expected behavior**
Should load the game and title screen correctly

**Desktop and VR (please complete the following information):**
 - Windows11
 - Nvidia GeForce RTX 3060
 - 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz

**Comment by creidhne-a16i** [comment]
For me doesn't work even without the loose file loader, crashes instead. Ver nightly 1204

[re2_framework_log.txt](https://github.com/user-attachments/files/24222476/re2_framework_log.txt)

[reframework_crash.dmp](https://github.com/user-attachments/files/24222477/reframework_crash.dmp)

**Comment by BrianHTC** [comment]
Same here

**Comment by ktrin-u** [comment]
Out of curiosity, I looked into @creidhne-a16i's `dmp` file and compared it with mine and we have similar errors. 

I'm curious what could be the root cause because my friend's install is running perfectly fine. Hell, I was playing fine last night until it wouldn't launch this today. I also noticed that MHWilds install in the logs above seem to be off the system drive? I wonder if that played a part in the issue.

Unfortunately, I am not knowledgeable in this field and I can barely understand the crash dump which contains what seems to be x86 low level stuff. 

I wonder if anyone knowledgeable here can explain what led to a null pointer exception. 

My system specs:
- Windows 11 24H2 OS Build 261000.4652
- RX 5700XT with 25.12.1 drivers
- R5 5600X

My log and crash dump:
- [reframework_crash.dmp](https://github.com/user-attachments/files/24261813/reframework_crash.dmp)

- [re2_framework_log.txt](https://github.com/user-attachments/files/24261846/re2_framework_log.txt)

```
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 0000000000000000
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000008
   Parameter[1]: 0000000000000000
Attempt to execute non-executable address 0000000000000000

PROCESS_NAME:  MonsterHunterWilds.exe

EXECUTE_ADDRESS: 0

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000008

EXCEPTION_PARAMETER2:  0000000000000000
```

**Comment by ktrin-u** [comment]
My issue got fixed as of [REF Nightly 01206 (50ec27753b294263590cd84b7420918f7ee2ae08)](https://github.com/praydog/REFramework-nightly/releases/tag/nightly-01206-50ec27753b294263590cd84b7420918f7ee2ae08)

**Comment by ferograd** [comment]
> My issue got fixed as of [REF Nightly 01206 (50ec27753b294263590cd84b7420918f7ee2ae08)](https://github.com/praydog/REFramework-nightly/releases/tag/nightly-01206-50ec27753b294263590cd84b7420918f7ee2ae08)

Tried that version of REFRAMEWORK and still stuck at a black screen in the latest build of MH Wilds.
Build 01207 didn't work either =(

Attached 

[re2_framework_log.txt](https://github.com/user-attachments/files/24300310/re2_framework_log.txt)

**Comment by Jkysler** [comment]
> > My issue got fixed as of [REF Nightly 01206 (50ec27753b294263590cd84b7420918f7ee2ae08)](https://github.com/praydog/REFramework-nightly/releases/tag/nightly-01206-50ec27753b294263590cd84b7420918f7ee2ae08)
> 
> Tried that version of REFRAMEWORK and still stuck at a black screen in the latest build of MH Wilds. Build 01207 didn't work either =(
> 
> Attached
> 
> [re2_framework_log.txt](https://github.com/user-attachments/files/24300310/re2_framework_log.txt)

I've had to verify my game files every time it gives me a black screen. I think it's safe to say to play the game without any mods until all the loose bugs are fixed.

**Comment by ferograd** [comment]
I think I've boiled it down to having certain mods that still have added custom .pak files which were causing this.

Removing all mods except some utility ones seems to have fixed that.
I too had to delete all .DLL and .PAK and re-verify files before trying again.
Seems to be working now with nightly 01207

Mod creators will have to re-do .pak files I suppose to match.

**Comment by creidhne-a16i** [comment]
v1207 also seemingly cured all my issues, other than old mods being incompatible. Will update to v1208 and continue testing and see how it goes.
