### ISSUE TITLE
RE7 DX12 Textures dropping quality

### ISSUE THREAD

**Issue by ShireDB** [praydog/REFramework#405]
I downloaded the latest RE7 build and got it working fine outside of the textures dropping to extremely pixelated oatmeal over time. The graphics settings work normally for roughly 10-15 minutes before they start to degrade. This occurred on a Valve Index through SteamVR, running off of a 3080 and an i7-10700K.

By the way, the healing softlock in the first Mia fight can be fixed via opening the inventory and using the heal through the menu prompt. 

Thanks for the amazing work on this mod, excited to see where it'll end up.

**Comment by wessberg** [comment]
I wrote this on Discord, but it seems fitting to write it here:

> I've found that in the DX12 builds of RE7 (possibly the other games too), and at least on my machine (Win 11, RX 6900 XT), there's something going on where textures seemingly don't load in their higher resolution versions and instead keep showing lower quality mipmaps. It is as if the game assumes that the distance of the player camera to the textured meshes is greater than it actually is. When I switch between the DX11 and DX12 builds of the game, I can immediately and deterministically reproduce the issue, simply by walking around in Zoe's Camper and inspecting the texture maps of the surrounding objects. Found a similar-sounding issue here on Github: https://github.com/praydog/REFramework/issues/405. Running the game in flatscreen/pancake mode eliminates this behavior, leading me to assume it must be somehow related to the VR camera position/behavior.  It is only affecting the DX12 build. Looking in the re7_config.ini, I can see options like StreamingVRAMSize{Lowest|Low|Standard|High|Highest}, leading me to believe that the updated engine has overhauled texture streaming, which could be a factor in this.

**Comment by d0x360** [comment]
Would it be possible to just replace the lower quality mipmaps with the highest quality ones?

Like a Very High End version of the mod?  All textures are always showing at their best possible quality.  Since it streams most textures it shouldn't really eat all the VRAM.  No more so than running Witcher 3 at the highest detail level for the entire world.  It works on 8 gig cards so this should work even better as the areas are generally smaller.

**Comment by Echodonut** [comment]
> I wrote this [on Discord](https://discord.com/channels/747967102895390741/926732294536986684/988521103850885200), but it seems fitting to write it here:
> 
> > I've found that in the DX12 builds of RE7 (possibly the other games too), and at least on my machine (Win 11, RX 6900 XT), there's something going on where textures seemingly don't load in their higher resolution versions and instead keep showing lower quality mipmaps. It is as if the game assumes that the distance of the player camera to the textured meshes is greater than it actually is. When I switch between the DX11 and DX12 builds of the game, I can immediately and deterministically reproduce the issue, simply by walking around in Zoe's Camper and inspecting the texture maps of the surrounding objects. Found a similar-sounding issue here on Github: #405. Running the game in flatscreen/pancake mode eliminates this behavior, leading me to assume it must be somehow related to the VR camera position/behavior.  It is only affecting the DX12 build. Looking in the re7_config.ini, I can see options like StreamingVRAMSize{Lowest|Low|Standard|High|Highest}, leading me to believe that the updated engine has overhauled texture streaming, which could be a factor in this.

I'm having the same issue. And I believe my install is DX12. How do you install the DX11 version of the game?

**Comment by d0x360** [comment]
Install dx11 version on steam by going to properties and telling steam to download the beta.

This texture issue was a big in the flat dx11 version at some point as well so it was fixed but has apparently come back?

**Comment by Echodonut** [comment]
> Install dx11 version on steam by going to properties and telling steam to download the beta. It's not really a beta it's just the dx11 version which they put up just for modding and VR mods breaking etc but they work in 12 now
> 
> I wonder if using the latest build of profile inspector (at least on nVidia) would let you force the best textures at all times. They did add that in and it's functional unlike in the old version or using just the regular cp
> 
> This texture issue was a big in the flat dx11 version at some point as well so it was fixed but has apparently come back?

I finally found some time to try this out. Sadly, it's breaking the whole thing for me. I have installed the dx11 version, and now it won't start. When I try to run the game, it opens, and the REframework VR overlay pops up, but it does not manage to pass input passthrough. It gets hung up there for a second, and then the executable just closes.

**Comment by praydog** [comment]
Install the old version of the mod, it's RE7_TDB49.zip.

**Comment by JMLX42** [comment]
@praydog so it means the "right"/only way to deal with those very low res textures is to switch to DX11?

**Comment by Echodonut** [comment]
I almost forgot to come back here. Thanks for the tip Praydog! Installing the DX11 version, and then using the old mod worked! Now it looks great :)

I'm still having some issues with the controller detection and button mapping, but that's a whole different issue. The visuals are marvelous, and it runs smoothly.

**Comment by d0x360** [comment]
I did forget when you said the mod didn't work,sorry about that.

**Comment by zmz125000** [comment]
#46
Dx11 fixed low quality texture, but makes the game very dark.

**Comment by Deen-co** [comment]
Has anyone found a solution to the problem other than using the DX11 version? Changing the version to DX11 did not help me. Textures are still the lowest quality almost always.

Maybe it is worth changing something in the REFramework settings?
